FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias para servidor web, conexión a MinIO y ML
RUN pip install fastapi uvicorn pydantic boto3 scikit-learn joblib pandas

# Copiar el código de la API
COPY main.py /app/

# Exponer el nuevo puerto
EXPOSE 8010

# Comando para iniciar el servidor de inferencia apuntando al puerto 8010
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8010"]