# Imagen base con Python y bibliotecas de ML
FROM python:3.11-slim

WORKDIR /app

# Copiar el archivo de requerimientos al contenedor
COPY requirements.txt /app/

# Instalar todas las dependencias y JupyterLab mediante pip estándar
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8025

# Comando por defecto para iniciar JupyterLab directamente
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8025", "--no-browser", "--allow-root", "--NotebookApp.token=''"]